//! AUTH
export const AUTH = 'AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_INITIAL = 'AUTH_INITIAL';
//! REGISTRATION
export const REGISTRATION = 'REGISTRATION';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
//! STATES
export const LOADING_STATES = 'LOADING_STATES';
export const SUCCESS_STATES = 'SUCCESS_STATES';
export const ERROR_STATES = 'ERROR_STATES';
//! STATES
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const SUCCESS_PRODUCTS = 'SUCCESS_PRODUCTS';
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS';
//! POSTS
export const LOADING_POSTS = 'LOADING_POSTS';
export const SUCCESS_POSTS = 'SUCCESS_POSTS';
export const ERROR_POSTS = 'ERROR_POSTS';
export const DONE_LOADING_POSTS = 'DONE_LOADING_POSTS';
export const SUCCESS_ADD_NEW_POSTS = 'SUCCESS_ADD_NEW_POSTS';
export const SUCCESS_DELETE_NEW_POSTS = 'SUCCESS_DELETE_NEW_POSTS';
//! PRODUCTS
export const GET_PRODUCTS_MAP = 'GET_PRODUCTS_MAP';
export const GET_PRODUCTS_MAP_SUCCESS = 'GET_PRODUCTS_MAP_SUCCESS';
export const GET_PRODUCTS_MAP_UPDATE = 'GET_PRODUCTS_MAP_UPDATE';
export const GET_PRODUCTS_MAP_DONE = 'GET_PRODUCTS_MAP_DONE';
